# Generated by Django 3.2.3 on 2021-07-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_salary_money_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
