# Generated by Django 3.2.3 on 2021-08-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210804_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money',
            old_name='user',
            new_name='user1',
        ),
    ]
