# Generated by Django 3.2.3 on 2021-08-04 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_rename_user_money_user1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='user1',
        ),
        migrations.AddField(
            model_name='money',
            name='user',
            field=models.OneToOneField(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
