# Generated by Django 3.2.3 on 2021-08-04 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20210804_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='user',
        ),
        migrations.AddField(
            model_name='money',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
