# Generated by Django 3.2.3 on 2021-08-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_money_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='category',
            field=models.CharField(choices=[('Продукты', 'Продукты'), ('Одежда', 'Одежда'), ('Машина', 'Машина')], default='Продукты', max_length=150),
        ),
    ]
